### ISSUE TITLE
Can't contact LDAP server (-1) for user when using openldap

### ISSUE THREAD

**Issue by Marketos-Damigos** [osixia/docker-phpLDAPadmin#100]
I am getting this error message when I try to login to the server as in #29 :

```
Unable to connect to LDAP server openldap
Error: Can't contact LDAP server (-1) for user
Failed to Authenticate to server
Invalid Username or Password.
```

If i use `ldapsearch` inside the container, using either the `env` variable or directly specifying `openldap:1389` it works perfectly. 
I have the following `docker-compose` file:

```
  openldap:
    image: bitnami/openldap:2.6-debian-10
    container_name: openldap
    environment:
      PUID: 1000
      PGID: 1000
      LDAP_ALLOW_ANON_BINDING: no
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: 
      LDAP_CUSTOM_LDIF_DIR: /ldifs
      LDAP_ROOT: dc=example,dc=com
    restart: always
    networks:
      web:
        ipv4_address: 172.20.0.43
    ports:
      - 1389:1389    
    volumes:
      - ./containers/openldap/ldifs:/ldifs:ro
      - ./containers/openldap/ldap:/bitnami/openldap
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - "traefik.http.routers.openldap-rtr.entrypoints=https"
      - "traefik.http.routers.openldap-rtr.rule=Host(`openldap.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.openldap-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.wiki-rtr.middlewares=middlewares-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.openldap-rtr.service=openldap-svc"
      - "traefik.http.services.openldap-svc.loadbalancer.server.port=1389"
      - "com.centurylinklabs.watchtower.enable=true"


  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap:1389"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "9214:80"
    command: --loglevel=debug
    depends_on:
      - openldap
    networks:
      web:
        ipv4_address: 172.20.0.45
    restart: always
```

**Comment by micobarac** [comment]
I have the same problem:

```
docker run -p 389:389 -p 636:636 \
  --hostname ldap.example.org \
  --name openldap \
  --detach osixia/openldap
```

```
$ docker exec openldap ldapsearch -x -H ldap://ldap.example.org -b dc=example,dc=org -D "cn=admin,dc=example,dc=org" -w admin
# extended LDIF
#
# LDAPv3
# base <dc=example,dc=org> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# example.org
dn: dc=example,dc=org
objectClass: top
objectClass: dcObject
objectClass: organization
o: Example Inc.
dc: example

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

```
docker run -p 6443:443 \
  --name phpldapadmin \
  --env PHPLDAPADMIN_LDAP_HOSTS=ldap.example.com \
  --detach osixia/phpldapadmin
```

![Screenshot 2023-02-06 at 13 44 15](https://user-images.githubusercontent.com/16001837/216974734-5c815126-5e27-47e4-b4d3-28dd3be4622e.png)

**Comment by micobarac** [comment]
Am I missing something here? I am using the default user and password.

**Comment by pplmx** [comment]
Hi, @Marketos-Damigos 
Do you fix it finally? When I use bitnami/opneldap, I encounter the same issue. ><

**Comment by baba2k** [comment]
You have to set the port to 389 inside the container when using internal docker network. You can do that with

```
      - LDAP_PORT_NUMBER=389
      - LDAP_LDAPS_PORT_NUMBER=636
```

**Comment by pplmx** [comment]
Hi, @baba2k 
Thanks for your comment. :)
It works fine.

**Comment by suityou01** [comment]
This is still a problem for me

```
services:
  ldap-server:
    image: osixia/openldap:1.5.0
    environment:
      - LDAP_ORGANISATION="My Co"
      - LDAP_DOMAIN="myco.co.uk"
      - LDAP_ADMIN_PASSWORD="fjfjsdf;sd"
      - LDAP_PORT_NUMBER=389
      - LDAP_LDAPS_PORT_NUMBER=636
  ldap-admin:
    depends_on:
      - ldap-server
    image: osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-server
    ports:
      - 443:443
```

```
Unable to connect to LDAP server ldap
Error: Can't contact LDAP server (-1) for user
```

Please help

**Comment by pplmx** [comment]
@suityou01 
`bitnami/openldap` instead of `osixia/openldap`.

**Comment by suityou01** [comment]
Isn't this the osixia repo? Can I get help for osixia images here?

**Comment by suityou01** [comment]
Can I get some help with this please?

I checked that the docker container could resolve the host name. It could not. I added a docker network to the stack and specified container names (not that this has any bearing on name resolution, just pointing out what I have done differently)

I am able to submit an LDAP query in the LDAP container.
I am able to ping the LDAP container from the LDAP-ADMIN container.

The problem persists.

Latest compose file

```
services:
  ldap-server:
    container_name: ldap-server
    image: osixia/openldap:1.5.0
    environment:
      - LDAP_ORGANISATION=myco
      - LDAP_DOMAIN=myco.co.uk
      - LDAP_ADMIN_PASSWORD=itsasecret
      - LDAP_PORT_NUMBER=389
      - LDAP_LDAPS_PORT_NUMBER=636
    ports:
      - 636:636
      - 389:389
    networks:
      - ldap-network
  ldap-admin:
    container_name: ldap_admin
    depends_on:
      - ldap-server
    image: osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-server
    ports:
      - 443:443
    networks:
      - ldap-network

networks:
  ldap-network:
    driver: bridge
```
