### ISSUE TITLE
Add customize ldap port support

### ISSUE THREAD

**Issue by dengshuan** [osixia/docker-phpLDAPadmin#13]
Hi, could you add customize ldap port support as documented [here](http://phpldapadmin.sourceforge.net/wiki/index.php/Server:server:host)

**Comment by osixia** [comment]
Hi, it's already possible :) 

in env.yaml set something like : 

```
PHPLDAPADMIN_LDAP_HOSTS:
  - ldap.example.org:
    - server:
      - port: 9879
```

or on docker run : 
`sudo docker run --env PHPLDAPADMIN_LDAP_HOSTS="[{'ldap.example.org': [{'server': [{'port': 9879}]}]}]"  -d osixia/phpldapadmin`

Please see README.md for more help
(note in the next release the --env option will change but it will be documented)

**Comment by kopax** [comment]
I am trying to achieve the same thing and I have tried your snippet within `docker-compose.yml`
```yml
version: '3'
services:
  openldap-app:
    image: osixia/openldap:1.2.4
    ports:
      - "390:389"
    environment:
      - LDAP_DOMAIN=domain.com
      - LDAP_ORGANISATION=domain
      - LDAP_ADMIN_PASSWORD=domain
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "[{'ldap.example.org': [{'server': [{'port': 9879}]}]}]"
      PHPLDAPADMIN_HTTPS: "false"
```

and it produce the following error when trying to access through http:

    Parse error: syntax error, unexpected 'ldap' (T_STRING), expecting ',' or ')' in /var/www/phpldapadmin/config/config.php on line 69

**Comment by Eliav2** [comment]
could you provide a complete docker-compose.yaml with the option to edit the port number?
currently i have 
```yaml
version: "3"

services:
  ldap:
    image: bitnami/openldap
    container_name: my-bitnami-ldap
    environment:
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_TLS=false
      - LDAP_PORT_NUMBER=1389
      - LDAP_LDAPS_PORT_NUMBER=636
    volumes:
      - bitnami_ldap_data:/bitnami/openldap
    ports:
      - "1389:1389"
      - "636:636"
    networks:
      - my-network

  ldap-admin:
    image: osixia/phpldapadmin
    container_name: my-ldap-admin-bitnami-setup
    environment:
      # PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'localhost': [{'server': [{'tls': False}, {'port': 1389}]}]}]"
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_HOSTS:
        - ldap.example.org:
          - server:
            - port: 1389
      # - PHPLDAPADMIN_LDAP_HOSTS=[{'ldap.example.org': [{'server': [{'port': 1389}]}]}]
      # - LDAP_PORT_NUMBER=1389
      # - LDAP_LDAPS_PORT_NUMBER=1636
    ports:
      - "8080:80"
    networks:
      - my-network

volumes:
  bitnami_ldap_data:

networks:
  my-network:
```

which of course does not work
