### ISSUE TITLE
Kubernetese - login failure. However other services can contact it just fine.

### ISSUE THREAD

**Issue by t5unamie** [osixia/docker-phpLDAPadmin#18]
I have a load of pods setup in Kubernetese. Other service like Jenkins, Artifactory and sonar can all connect to the LDAP server.

However when I login to the PHPadmin server now. I get the following error.

This was working, confused on why it's not. Is there away to parse out the current values if I exec in to the container?

``` error
error   Unable to connect to LDAP server openldapsvc.default.cluster.local
Error: Can't contact LDAP server (-1) for user
error   Failed to Authenticate to server
Invalid Username or Password.
```

Openldap service below. -

``` yaml

apiVersion: v1
kind: Service
metadata:
  name: openldapsvc
  labels:
    app: openldap
spec:
  ports:
  - port: 389
    protocol: TCP
    name: ldap
  selector:
    app: openldap

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openldap
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.1.2
        env:
        -
          name: "LDAP_DOMAIN"
          value: "example.io"
        -
          name: "LDAP_ORGANISATION"
          value: "DDUK"
        -
          name: "LDAP_ROOTPASS"
          value: "root"
        -
          name: "LDAP_ADMIN_PWD"
          value: "root"
        ports:
        - containerPort: 389
          name: ldap
        volumeMounts:
        - mountPath: /var/lib/ldap
          name: data
        - mountPath: /etc/ldap/slapd.d
          name: config
        - mountPath: /etc/ldap/ssl
          name: ssl
      volumes:
        - name: data
        # This AWS EBS volume must already exist.
          awsElasticBlockStore:
            volumeID: @@@volume-id1@@@
            fsType: ext4
        - name: config
        # This AWS EBS volume must already exist.
          awsElasticBlockStore:
            volumeID: @@@volume-id2@@@
            fsType: ext4
        - name: ssl
        # This AWS EBS volume must already exist.
          awsElasticBlockStore:
            volumeID: @@@volume-id3@@@
            fsType: ext4
```

php pod

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: openldapadminsvc
  labels:
    app: openldapadmin
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    protocol: TCP
    name: https
    targetPort: 443
  selector:
    app: openldapadmin

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: openldapadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openldapadmin
    spec:
      containers:
      - name: openldapadmin
        image: osixia/phpldapadmin:0.6.7
        env:
        -
          name: "PHPLDAPADMIN_LDAP_HOSTS"
          value: "#PYTHON2BASH:[{'openldapsvc.default.cluster.local': [{'server': [{'tls': False}]},{'login': [{'bind_id': 'cn=admin,dc=example,dc=io'}]}]}, 'openldapsvc.default.cluster.local']"
        ports:
        - containerPort: 443
          name: https
```
