### ISSUE TITLE
Error in config.php, PHPLDAPADMIN_LDAP_HOSTS/docker-compose.yml

### ISSUE THREAD

**Issue by jcgruenhage** [osixia/docker-phpLDAPadmin#25]
When I try to access phpldapadmin, I get `Parse error: syntax error, unexpected '}' in /container/service/phpldapadmin/assets/config.php on line 68`. Line 68 should contain the ldap host, so I assume that there is an error with that variable. 

Here is the excerpt from my docker-compose.yml:
```
version: '2'
services:
        openldap:
                image:  dinkel/openldap
                container_name: openldap
                environment:
                        - SLAPD_PASSWORD=***REMOVED_SENSITIVE_VALUE***
                        - SLAPD_DOMAIN=***REMOVED_SENSITIVE_VALUE***
                volumes:
                        - ./openldap/etc_ldap:/etc/ldap
                        - ./openldap/var_lib_ldap:/var/lib/ldap
        
        phpldapadmin:
                image:  osixia/phpldapadmin
                container_name: phpldapadmin
                environment:
                        - PHPLDAPADMIN_HTTPS=false
                        - PHPLDAPADMIN_LDAP_HOSTS=openldap
```
