### ISSUE TITLE
Doc: Mention possibility of \" for inline PHPLDAPADMIN_LDAP_HOSTS

### ISSUE THREAD

**Issue by j-maas** [osixia/docker-phpLDAPadmin#28]
The docs (main README) could mention how to customize the phpLDAPAdmin-Config using arrays.

### Current state
The YAML-example uses an array for `force_may`:
```
- ldap.example.org:
  - server:
    - tls: true
    - port: 636
    - force_may: array('uidNumber','gidNumber','sambaSID')
  - login:
    - bind_id: cn=admin,dc=example,dc=org
    - bind_pass: p0p!
  - auto_number:
    - min: 1000
- ldap2.example.org
- ldap3.example.org
```
However the inline example does not use any array:
```
docker run --env PHPLDAPADMIN_LDAP_HOSTS="#PYTHON2BASH:[{'ldap.example.org': [{'server': [{'tls': True}]},{'login': [{'bind_id': 'cn=admin,dc=example,dc=org'}]}]}, 'ldap2.example.org', 'ldap3.example.org']" --detach osixia/phpldapadmin:0.6.12
```
### Proposed solution
For example, the complete YAML-example could be translated into inline. (This might be too verbose, though). The need for escaping might be spelled out explicitely.
```
docker run --env PHPLDAPADMIN_LDAP_HOSTS="#PYTHON2BASH:[{'ldap.example.org': [{'server': [{'tls': True}, {'port': 636}, {'force_may': \"array('uidNumber','gidNumber','sambaSID')\"}]}, {'login': [{'bind_id': 'cn=admin,dc=example,dc=org'}, {'bind_pass': 'p0p!'}]}, {'auto_number': [{'min': 1000}]}]}, 'ldap2.example.org', 'ldap3.example.org']" --detach osixia/phpldapadmin:0.6.12
```
### Motivation
I spent a few hours trying to define multiple `base` DNs for my server to be able to access the `cn=config`. I finally realized that it is possible to escape the inner `"` that are put around the array.

If there is an alternative way of customizing the phpLDAPAdmin-Config, then maybe it could be clarified. The docs suggest there is, but I do not understand what it is (apart from maybe mounting a volume to `image/environment/default.yaml` thus overriding the default.yml?).
