### ISSUE TITLE
Undefined index PATH_INFO on lib/common.php@L42

### ISSUE THREAD

**Issue by maddie** [osixia/docker-phpLDAPadmin#53]
Tested on v0.7.2 (latest) and v0.7.1, running with docker-compose.

When I try to access "http://server-ip:8080/" or "http://server-ip:8080/phpldapadmin", Chrome returns "too many redirects" error, and in the container log as below:

```
phpldapadmin      | [21-Jan-2019 09:20:19] WARNING: [pool www] child 1627 said into stderr: "NOTICE: PHP message: PHP Notice:  Undefined index: PATH_INFO in /var/www/phpldapadmin/lib/common.php on line 42"
phpldapadmin      | [Mon Jan 21 09:20:19.597330 2019] [proxy_fcgi:error] [pid 1522:tid 140711718549248] [client 192.168.123.123:15536] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: PATH_INFO in /var/www/phpldapadmin/lib/common.php on line 42\n'
phpldapadmin      | 192.168.123.123 - - [21/Jan/2019:09:20:19 +0000] "GET /index.php HTTP/1.0" 302 558 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
```

Falling back to `0.6.12` fixes the problem. My `docker-compose.yml` as below:

```
[... openldap container ...]
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
    ports:
      - "8080:80"
      #- "6443:6443"
    depends_on:
      - openldap
```
