### ISSUE TITLE
Weird caching issue with PHPLDAPADMIN_LDAP_HOSTS

### ISSUE THREAD

**Issue by stefandesu** [osixia/docker-phpLDAPadmin#70]
Hi, I think I found a weird caching issue with the environment variable `PHPLDAPADMIN_LDAP_HOSTS`. Here's my docker-compose file:

```yaml
version: "3"
services:
  openldap:
    image: osixia/openldap
    networks:
      - traefik
    environment:
      LDAP_ORGANISATION: "${LDAP_ORG}"
      LDAP_DOMAIN: "${LDAP_DOMAIN}"
      LDAP_BASE_DN: "${LDAP_BASEDN}"
      LDAP_ADMIN_PASSWORD: "${LDAP_ADMIN_PASS}"
    hostname: openldap
    volumes:
      - ./data/ldap:/var/lib/ldap
      - ./data/slapd.d:/etc/ldap/slapd.d
    restart: always
  phpldapadmin:
    image: osixia/phpldapadmin
    networks:
      - traefik
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:ldapadmin.${DOMAIN}
    restart: always
networks:
  traefik:
    external:
      name: traefik_webgateway
```

The issue is that even if I change `PHPLDAPADMIN_LDAP_HOSTS` in the docker-compose file, the phpLDAPadmin site still shows and uses the old host. Only after I renamed the `phpldapadmin` service to `phpldapadmin2`, it finally got the change and it works now (took me an hour because I didn't get it...). As you can see, I haven't mounted any volumes in the `phpldapadmin` service, so there should be no persistent data, and the environment variable is empty if I `echo` it on the console. What is going on?

By the way, I thought that this might be the cause for problems described in #12.
