### ISSUE TITLE
TLS doesn't work - Error: Confidentiality required (13) for user

### ISSUE THREAD

**Issue by J7mbo** [osixia/docker-phpLDAPadmin#72]
TLS configuration doesn't work. I can run:

```
docker exec <openldap_container> ldapsearch -x -H ldaps://localhost -b dc=mydomain,dc=com -D "cn=admin,dc=mydomain,dc=com" -w admin
```

It works! However in the UI I get:

![image](https://user-images.githubusercontent.com/2657310/80040563-9e416e00-84fa-11ea-8069-02fb32ed64fe.png)

Here is docker-compose:

```
ldapadmin:
        image: osixia/phpldapadmin:latest
        hostname: ldapadmin
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=openldap
            - PHPLDAPADMIN_HTTPS=false
            - PHPLDAPADMIN_TRUST_PROXY_SSL=true
            - PHPLDAPADMIN_LDAP_CLIENT_TLS=true
            - LDAP_CLIENT_SSL_HELPER_PREFIX=ldaps
```

LDAP server logs:

```
5ea0c90b conn=1027 fd=12 ACCEPT from IP=10.0.1.7:35904 (IP=0.0.0.0:389)
5ea0c90b conn=1027 op=0 BIND dn="cn=admin,dc=mydomain,dc=com" method=128
5ea0c90b conn=1027 op=0 RESULT tag=97 err=13 text=confidentiality required
5ea0c90b conn=1027 op=1 UNBIND
5ea0c90b conn=1027 fd=12 closed
```
-----

I have tried:

Copying the CA, cert and key from openldap container in `/container/service/:ssl-tools/assets/default-ca/default-ca.pem` and using them with:

- `PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME`
- `PHPLDAPADMIN_LDAP_CLIENT_TLS_CRT_FILENAME`
- `PHPLDAPADMIN_LDAP_CLIENT_TLS_KEY_FILENAME`

**Still the same problem**. Why?

**Comment by J7mbo** [comment]
I solved it with help from: #64 and #33. My compose now looks like this:

```
ldapadmin:
        image: osixia/phpldapadmin:latest
        hostname: ldapadmin
        environment:
            PHPLDAPADMIN_LDAP_CLIENT_TLS: "true"
            PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'openldap': [{'server': [{'tls': True}]}]}]"
            PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME: openldapca.pem
```

Note that `openldapca.pem` was copied from `default-ca.pem` from within the openldap container as described previously. Thanks!
