### ISSUE TITLE
TLS/SSL (ldaps) is broken

### ISSUE THREAD

**Issue by pini-gh** [osixia/docker-phpLDAPadmin#74]
Hi,
My undertanding is that the generated configuration for TLS/SSL is broken. The ldap-client startup.sh script generates `~www-data/.ldaprc` referencing a dummy key/cert pair preventing the connection via ldaps://.

Manually removing `~www-data/.ldaprc` fixes the problem.

BTW, any reason for not writing this piece of configuration into /etc/ldap/ldap.conf? It took me *hours* to figure out there was a `.ldaprc` in the way.

Docker compose file :
```
  phpldapadmin:
    image: osixia/phpldapadmin:stable
    container_name: phpldapadmin
    environment:
      # http://phpldapadmin.sourceforge.net/wiki/index.php/Server:server:host
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldaps://ldap.pini.fr:636': [{'server': [{'port': 0},{'base': \"array('cn=config','dc=pini,dc=fr')\"}]}]}]"
      PHPLDAPADMIN_LDAP_CLIENT_TLS_CA_CRT_FILENAME: "chain.pem"
      PHPLDAPADMIN_HTTPS: "false" # behind a reverse proxy
    volumes:
      - certs:/container/service/ldap-client/assets/certs
    expose:
      - "80"
```

Thanks.
