### ISSUE TITLE
Please do not chmod my certificates

### ISSUE THREAD

**Issue by williamdes** [osixia/docker-phpLDAPadmin#81]
```yml

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        networks:
            example_mail_infra:
                aliases:
                    - ldap-admin.example.com
        environment:
            PHPLDAPADMIN_LDAP_HOSTS: "ldap.example.com"
            PHPLDAPADMIN_HTTPS_CRT_FILENAME: "fullchain.cer"
            PHPLDAPADMIN_HTTPS_KEY_FILENAME: "example.com.key"
            PHPLDAPADMIN_HTTPS_CA_CRT_FILENAME: "ca.cer"
        volumes:
            - ${ACME_HOME_DIR}/example.com:/container/service/phpldapadmin/assets/apache2/certs:ro
        ports:
            - "8080:80"
        depends_on:
            - openldap
```

```
phpldapadmin    | *** Running /container/run/startup/:ssl-tools...
phpldapadmin    | *** Running /container/run/startup/:syslog-ng-core...
phpldapadmin    | *** Running /container/run/startup/ldap-client...
phpldapadmin    | No certificate file and certificate key provided, generate:
phpldapadmin    | /container/service/ldap-client/assets/certs/ldap-client.crt and /container/service/ldap-client/assets/certs/ldap-client.key
phpldapadmin    | 2020/12/06 00:21:23 [INFO] generate received request
phpldapadmin    | 2020/12/06 00:21:23 [INFO] received CSR
phpldapadmin    | 2020/12/06 00:21:23 [INFO] generating key: ecdsa-384
phpldapadmin    | 2020/12/06 00:21:23 [INFO] encoded CSR
phpldapadmin    | 2020/12/06 00:21:23 [INFO] signed certificate with serial number 588091058469135729676991556202186249099938418544
phpldapadmin    | Link /container/service/:ssl-tools/assets/default-ca/default-ca.pem to /container/service/ldap-client/assets/certs/ldap-ca.crt
phpldapadmin    | *** Running /container/run/startup/phpldapadmin...
phpldapadmin    | Set apache2 https config...
phpldapadmin    | chmod: changing permissions of '/container/service/phpldapadmin/assets/apache2/certs/fullchain.cer': Read-only file system
phpldapadmin    | chmod: changing permissions of '/container/service/phpldapadmin/assets/apache2/certs/example.com.key': Read-only file system
phpldapadmin    | *** /container/run/startup/phpldapadmin failed with status 1
phpldapadmin    | 
phpldapadmin    | *** Killing all processes...
```

Do the same as https://github.com/osixia/docker-openldap/blob/7ce084bab1f9016830548558241fdefb60862482/image/service/slapd/startup.sh#L88 ;)
