### ISSUE TITLE
Service exception on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by cshanxiao** [osixia/docker-phpLDAPadmin#92]
Excute me, I meet an exception when deploy service on Ubuntu 20.04.3 LTS:

root@xxx:/data/container# cat docker-compose.yml 
```
version: '2'
services:
  slapd:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: example
      LDAP_DOMAIN: example.com
      LDAP_ADMIN_PASSWORD: secret
    ports:
      - 389:389
    networks:
      network-base:

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: slapd
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - 8080:80
    depends_on:
      - slapd
    networks:
      network-base:

networks:
   network-base:
      ipam:
         config:
         - subnet: 172.25.25.0/24
           gateway: 172.25.25.1
```

then I start the container with command:
docker-compose up -d

after service started, I visit the service with google brower: 
http://xxx.xxx.xxx.xxx:8080

but the brower renturns error:
ERR_TOO_MANY_REDIRECTS
