### ISSUE TITLE
How do define ldap port number in docker-compose environment section?

### ISSUE THREAD

**Issue by benisai** [osixia/docker-phpLDAPadmin#94]
Hello, my ldap is on a non standard port. How do I define this port in my docker-compose file?

**Comment by KleyLima** [comment]
I was struggling with this too. I manage with this config:
```
phpldapadmin:
    restart: unless-stopped
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ""#PYTHON2BASH:[{'YOUR_HOST': [{'server': [{'tls': False}, {'port': YOUR_PORT}]}]}]""
```
