### ISSUE TITLE
`invalid type` error when using YAML for `PHPLDAPADMIN_LDAP_HOSTS`

### ISSUE THREAD

**Issue by The-Judge** [osixia/docker-phpLDAPadmin#96]
When I am trying to set `PHPLDAPADMIN_LDAP_HOSTS` to some YAML structure as shown in the docs, I end up with an error, saying:

> # docker-compose up -d
> ERROR: The Compose file './docker-compose.yml' is invalid because:
> services.phpldapadmin.environment.PHPLDAPADMIN_LDAP_HOSTS contains [{"ldap.example.com": [{"server": [{"tls": "true"}]}, {"login": [{"bind_id": "cn=admin,dc=example,dc=com"}]}]}], which is an invalid type, it should be a string, number, or a null

My docker-compose.yml file:

```YAML
version: '3.2'

services:

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS:
        - ldap.example.com:
          - server:
            - tls: "true"
          - login:
            - bind_id: "cn=admin,dc=example,dc=com"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - 80
    hostname: "ldap.example.com"
```
