### ISSUE TITLE
Error bootstraping: "unterminated `s' command"

### ISSUE THREAD

**Issue by daper** [osixia/docker-phpLDAPadmin#97]
When I set the variable `PHPLDAPADMIN_LDAP_HOSTS` like:
```
PHPLDAPADMIN_LDAP_CLIENT_TLS: "false"
PHPLDAPADMIN_LDAP_HOSTS_FRIENDLY: "true"
PHPLDAPADMIN_LDAP_HOSTS: |
  - server1:
    - server:
      - name: openldap
      - host: example.com 
      - tls: "false"
      - port: 389
    - login:
      - auth_type: session
      - bind_id: "cn=admin,dc=example,dc=com"
      - bind_pass: "admin"
```
And when the container bootstraps it fails with:
```
Bootstap phpLDAPadmin...
tr: write error: Broken pipe
tr: write error
sed: -e expression #1, char 94: unterminated `s' command
*** /container/run/startup/phpldapadmin failed with status 1
```
